---
title: "TCM-QAQC"
author: "Christina Bonsell"
date: "October 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(oce)
library(cowplot)
```

# A cleaned-up version of [TCMworkup.Rmd](https://github.com/cbonsell/ble-instumentation/blob/master/tCMworkup.Rmd) that only spits out final dataset and plots

Important info

* Looks like JALD2 got knocked out by ice? Data flagged as BAD
* Suspiciously high currents at EELD1 June 29- Jul4 flagged as QM (questionable)
* EWLD1 battery died June 15 2019


Read in data
```{r, message=FALSE}
source('scr/TCMdata_import.R')
#fill in daylight savings time issue (result from keeping format in Alaska time)
TCM_Temp$DT[is.na(TCM_Temp$DT)]<-as.POSIXct("2019-03-10 02:00:00")
TCM_Curr$DT[is.na(TCM_Curr$DT)]<-as.POSIXct("2019-03-10 02:00:00")
```

Flag JALD2 and EELD1

```{r flags}
TCM_Curr<-TCM_Curr%>%
  mutate(flags=
           case_when(Station=="JALD2"& DT>as.POSIXct("2018-08-27 01:00:00", tz="US/Alaska")~"BAD",
                    Station=="EELD1"& DT>as.POSIXct("2019-06-29 05:00:00", tz="US/Alaska")&DT<as.POSIXct("2019-07-04 20:00:00", tz="US/Alaska") ~"QM"))



```
Final plots
```{r plot, fig.width=11, fig.height=8, fig.fullwidth=TRUE}
ggplot(TCM_Curr, aes(DT, Speed_cm_s))+
  geom_point(aes(color=flags))+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()

ggplot(TCM_Curr, aes(DT))+
  geom_line(aes(y=Vel_N,color="Vel_N"))+
  geom_line(aes(y=Vel_E,color="Vel_E"))+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()+
  scale_color_manual(breaks = c("Vel_N", "Vel_E"),values = c("Vel_N"="black", "Vel_E"="blue"))


ggplot(TCM_Temp, aes(DT, Temperature))+
  geom_line(aes(color=Station))+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()
```

write table

```{r}
TCM2018to2019 <- full_join(TCM_Temp,TCM_Curr,by=c("Station","DT")) %>% 
  select(-flags,flags) #this join will be conservative (final table will not include temps for which there aren't current measurements)

write.csv(TCM2018to2019, "results/BLE LTER TCM2018to2019.csv")
```
Final table: [BLE LTER TCM2018to2019.csv](https://github.com/cbonsell/ble-instrumentation/blob/master/results/BLE%20LTER%20TCM2018to2019.csv)
