---
title: "LTER2019TCMworkup from raw"
author: "Christina Bonsell"
date: "October 4, 2019"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(oce)
library(cowplot)
```

#Looks like JALD2 got knocked out by ice?
#JALD1+KALD1+KALD2: very consistant low winter current in those lagoons?
#EWLD1 died June 15

```{r look_at_data, echo=FALSE, message=FALSE, warning=FALSE}
source('scr/TCMdata_import.R')

ggplot(TCM_Temp, aes(DT, Temperature))+
  geom_line(aes(color=Station))+
  theme_cowplot()

ggplot(TCM_Curr, aes(DT, Speed_cm_s))+
  geom_line(aes(color=Station))+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()

ggplot(TCM_Curr, aes(DT, Vel_N))+
  geom_line(color="blue")+
  geom_line(aes(DT, Vel_E), color="black")+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()
```

```{r stickplot, echo=FALSE, message=FALSE, warning=FALSE}
layout(matrix(c(1,2,3,4,5,6,7), 7), 30,c(10,10,10,10,10,10,10))
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="EELD1"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="EELD1"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="EELD1"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="EELD2"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="EELD2"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="EELD2"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="EWLD1"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="EWLD1"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="EWLD1"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="EWLD2"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="EWLD2"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="EWLD2"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="KALD1"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="KALD1"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="KALD1"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="KALD2"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="KALD2"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="KALD2"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
plotSticks(TCM_Curr$DT[TCM_Curr$Station=="JALD1"], 1, 
           TCM_Curr$Vel_E[TCM_Curr$Station=="JALD1"], 
           TCM_Curr$Vel_N[TCM_Curr$Station=="JALD1"], 
           yscale=50, ylab='', yaxt='n', length=0, frame.plot=F,xaxt='n')
axis.POSIXct(1,at = seq(min(TCM_Curr$DT), max(TCM_Curr$DT), by = "1 months"), format = "%b")

```


#Flag JALD2 and EELD1

* JALD2 after 2018-08-27 04:00:00 (bad data, knocked out by ice?)

* EELD1 between 2019-06-29 05:00:00 and 2019-07-04 20:00:00 (questionably high measurements)

```{r flags, message=FALSE, warning=FALSE}
#note that data is actually in US/Alaska, but why write more R code to deal with that?

TCM_Curr<-TCM_Curr%>%
  mutate(flags=
           case_when(Station=="JALD2"& DT>as.POSIXct("2018-08-27 04:00:00", tz="UTC")~"BAD",
                    Station=="EELD1"& DT>as.POSIXct("2019-06-29 05:00:00", tz="UTC")&DT<as.POSIXct("2019-07-04 20:00:00", tz="UTC") ~"QM"))
```

Plots to show where flags are

```{r flagplots, echo=FALSE}
ggplot(TCM_Curr, aes(DT, Speed_cm_s))+
  geom_point(aes(color=flags))+
  facet_wrap(~Station, scales="free")+
  theme_cowplot()

TCM_Curr %>% filter(Station=="JALD2"&
                    DT<as.POSIXct("2018-08-28 01:00:00", tz="UTC")) %>% 
  ggplot(aes(DT, Speed_cm_s))+
  geom_line(aes(color=flags))+
  theme_cowplot()

TCM_Curr %>% filter(Station=="EELD1"&
                    DT>as.POSIXct("2019-06-28 01:00:00", tz="UTC")&
                      DT<as.POSIXct("2019-07-05 01:00:00", tz="UTC")) %>% 
  ggplot(aes(DT, Speed_cm_s))+
  geom_point(aes(color=flags))+
  theme_cowplot()

```






